# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bill Howe
tagline:          Data. Science. Education.
url:              http://escience.washington.edu
paginate:         1
baseurl:          /
author:
  name:           Bill Howe
  url:            http://homes.cs.washington.edu/~billhowe/
  email:          billhowe@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/billhowe/billhowe.github.io
